# This is a basic workflow to help you get started with Actions

name: scp_to_machines

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  copy-to-nectar:
    name: nectar
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
        
      - name: Copy files
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        with:
          host: ${{ secrets.NECTAR_HOST }}
          user: ${{ secrets.NECTAR_USERNAME }}
          key: ${{ secrets.NECTAR_PRIVATE_KEY }}
          
          scp: |
            app.R => /srv/shiny-server/lwells
            cleanup.R => /srv/shiny-server/lwells
            EarlySowingSites.csv => /srv/shiny-server/lwells
            
            data/getIt.bomNC.R => /tmp/ssh_files
            data/getIt.Hindcast.R => /tmp/ssh_files
            RunHindcast.R => /tmp/ssh_files
            Template_hindcast.apsim => /tmp/ssh_files
            apsimFileGenerator.R => /tmp/ssh_files
            simCollector.R => /tmp/ssh_files
            Template.R => /tmp/ssh_files
            EarlySowingSites.csv => /tmp/ssh_files
            
          last_ssh: |
            cd /srv/shiny-server/lwells
            chgrp uploaders app.R cleanup.R EarlySowingSites.csv
            scp /tmp/ssh_files/* peter_workstation:/home/data/access-s/met
            rm -rf /tmp/ssh_files
          
