# This is a basic workflow to help you get started with Actions

name: scp_to_machines

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  copy-to-nectar:
    name: nectar
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
        
      - name: Copy to nectar
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        with:
          host: ${{ secrets.NECTAR_HOST }}
          user: ${{ secrets.NECTAR_USERNAME }}
          key: ${{ secrets.NECTAR_PRIVATE_KEY }}
          scp: testfile* => /home/lwells

